In [1]:
import numpy as np
import pandas as pd

# gauss elimination with partial pivoting

In [2]:
def geli_par_piv(ip_mat):
    fmat=ip_mat
    mat_shape=fmat.shape
    #pmat is a 3d array where number of stacks is equal to total number of permutations(row interchange)
    pmat=np.zeros([min(mat_shape[0]-1,mat_shape[1]),mat_shape[0],mat_shape[0]],dtype=np.float)#(1.)only for square matrices #(2.)i will make it an optional output of the function
    lmat=np.identity(mat_shape[0],dtype=np.float)#initialising unit lower triangular matrix
    for col_i in range(0,min(mat_shape[0]-1,mat_shape[1])):
        temp_pivot_index=col_i
        temp_pivot=fmat[col_i,col_i]
        pmat[col_i,:,:]=np.identity(mat_shape[0])#careful! there is a subtle difference in indexing for defining and that for slicing.
        for temp_checking_index in range(col_i+1,mat_shape[0]):
            #finding rows to swap 
            if (abs(temp_pivot)<abs(fmat[temp_checking_index,col_i])):
                temp_pivot_index=temp_checking_index
                temp_pivot=fmat[temp_checking_index,col_i]
        print(" -------------STEP NUMBER ",col_i, "-------------")
        print("temp_pivot_index is=",temp_pivot_index)
        print("col_i is=",col_i)
        #swapping rows
        #here i also need to keep track of indices of those rows which are interchanged (this is important for LU factorisation)
        if (temp_pivot_index != col_i):
            fmat[[col_i,temp_pivot_index],:] = fmat[[temp_pivot_index,col_i],:] #swapping rows #https://stackoverflow.com/questions/54069863/swap-two-rows-in-a-numpy-array-in-python
            pmat[col_i,[col_i,temp_pivot_index],:] = pmat[col_i,[temp_pivot_index,col_i],:] #permutation matrix p_i at ith step
            print("fmat after partial pivoting")
            print(fmat)
            lmat[[col_i,temp_pivot_index],0:col_i]=lmat[[temp_pivot_index,col_i],0:col_i]#important step
        #making elements below the pivot entries as zero
        print("associated unit lower triangular matrix till low")
        print(lmat)
        for temp_red_zero_index in range(col_i+1,mat_shape[0]):
            subtrahend_vector=fmat[col_i,:]*(fmat[temp_red_zero_index,col_i]/fmat[col_i,col_i])
            print("subtrahend vector=")
            print(subtrahend_vector)
            print("multiplier is:")
            print(fmat[temp_red_zero_index,col_i]/fmat[col_i,col_i])
            lmat[temp_red_zero_index,col_i]=(fmat[temp_red_zero_index,col_i]/fmat[col_i,col_i])
            fmat[temp_red_zero_index,:]=np.subtract(fmat[temp_red_zero_index,:],subtrahend_vector)
            print("NOW AFTER REDUCING ELEMENTS BELOW PIVOT ZERO THE INPUT MATRIX FMAT IS=")
            print(fmat)
            print("associated unit lower triangular matrix")
            print(lmat)
        print("3d permutation matrix is:")
        print(pmat)

    return fmat
            
        

# main program

In [3]:
#trial_mat=np.array([[1,17,3,4,5],[6,7,8,9,10],[23,45,1,23,532],[5,22,3,12,0],[2,5,3,6,11]],dtype=np.float)#dtype is important to mention
#trial_mat=np.array([[3,4],[8,9],[1,23]],dtype=np.float)
#trial_mat=np.array([[0.02,0.01,0,0,0.02],[1,2,1,0,1],[0,1,2,1,4],[0,0,100,200,800]],dtype=np.float)
#trial_mat=np.array([[2,2,3],[4,5,6],[1,2,4]],dtype=np.float)#eg. 5.6
#trial_mat=np.array([[-1,1,6],[-4,-8,6],[2,16,23]],dtype=np.float)
#trial_mat=np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]],dtype=np.float)
trial_mat=np.array([[1,2,4],[4,5,6],[7,8,9]],dtype=np.float)
#trial_mat=np.array([[1,1,0,0.0001],[0,2,1,0.0001],[0,0,3,-1.666]],dtype=np.float)
c=geli_par_piv(trial_mat)
print("c matrix is=")
print(c)

 -------------STEP NUMBER  0 -------------
temp_pivot_index is= 0
col_i is= 0
associated unit lower triangular matrix till low
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
subtrahend vector=
[0. 0. 0. 0.]
multiplier is:
0.0
NOW AFTER REDUCING ELEMENTS BELOW PIVOT ZERO THE INPUT MATRIX FMAT IS=
[[ 1.000e+00  1.000e+00  0.000e+00  1.000e-04]
 [ 0.000e+00  2.000e+00  1.000e+00  1.000e-04]
 [ 0.000e+00  0.000e+00  3.000e+00 -1.666e+00]]
associated unit lower triangular matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
subtrahend vector=
[0. 0. 0. 0.]
multiplier is:
0.0
NOW AFTER REDUCING ELEMENTS BELOW PIVOT ZERO THE INPUT MATRIX FMAT IS=
[[ 1.000e+00  1.000e+00  0.000e+00  1.000e-04]
 [ 0.000e+00  2.000e+00  1.000e+00  1.000e-04]
 [ 0.000e+00  0.000e+00  3.000e+00 -1.666e+00]]
associated unit lower triangular matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3d permutation matrix is:
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
 -------------STEP NUMBER  1 -------------
t

#### List of links I used as reference for syntax , mathematics, example problems etc. Also included links to some stuff i found interesting!
1. PA=LU Factorisation youtube channel Antonio Mastroberardino:: https://www.youtube.com/watch?v=f6RT4BI4S7M
2. example probelm 4X4 matrix:: https://math.stackexchange.com/questions/485513/what-are-pivot-numbers-in-lu-decomposition-please-explain-me-in-an-example
3. https://hal-univ-paris13.archives-ouvertes.fr/hal-01809975/document: Efficient algorithms to perform linear algebra operations on 3D arrays in vector languages - research paper by Francois Cuvelier. (seems interesting, will read it later for sure) 
 



#### MISTAKES I MADE:
1. swapping rows:             #For anybody else confused about the notation a[[0, 2]] is shorthand for a[[0, 2], :] 
            #so this selects the submatrix consisting of all of rows 0 and 2. To interchange columns, one would use a[:, [0, 2]] = a[:, [2, 0]]
            '''
            swap_temp_vec=fmat[col_i,:]
            print("swap_temp_vec is=")
            print(swap_temp_vec)
            fmat[col_i,:]=fmat[temp_pivot_index,:]#+1
            print("NOW swap_temp_vec is=")#good that i came across this! it is one of the most important feature of python
            print(swap_temp_vec)
            fmat[temp_pivot_index,:]=swap_temp_vec
            '''
2. always mention the data type of your numpy array np.array(values,dtype=e.g. float)
3. SHAPE of numpy array : https://opensourceoptions.com/blog/numpy-array-shapes-and-reshaping-arrays/#:~:text=3D%20arrays,order%20layers%2C%20rows%2C%20columns. i was a little confused for 3d arrays. the shape format used by numpy is (layers,rows,columns)